### ISSUE TITLE
Image of products

### ISSUE THREAD

**Issue by nguyenhungvku** [ShokhrukhbekYuldoshev/Nectar#3]
I don't know why i'm still can't see the image of products please help me
![image](https://github.com/ShokhrukhbekYuldoshev/Nectar/assets/100670771/9d795d3c-74e1-4c86-9214-7f7f98b6ee12)

**Comment by nguyenhungvku** [comment]
i'm already install v1.0.0

**Comment by ShokhrukhbekYuldoshev** [comment]
Because I didn't upload product images to firebase storage, so it uses placeholder. You can use your own database if you like to add images.
